---
title: "Activity Monitoring Data Analysis"
author: "Karishma Pandey"
date: "`r Sys.Date()`"
output: html_document
---

## Loading and preprocessing the data

```{r echo=TRUE}
data <- read.csv("../data/activity.csv")
head(data)
str(data)
summary(data)
```

---

## What is mean total number of steps taken per day?

```{r echo=TRUE}
# Remove NA values
data_no_na <- data[!is.na(data$steps), ]

# Calculate total steps per day
total_steps_per_day <- aggregate(steps ~ date, data = data_no_na, sum)

# Histogram
hist(total_steps_per_day$steps,
     main = "Histogram of Total Steps per Day",
     xlab = "Total Steps per Day",
     col = "lightblue")

# Mean and Median
mean_steps <- mean(total_steps_per_day$steps)
median_steps <- median(total_steps_per_day$steps)

mean_steps
median_steps
```

---

## What is the average daily activity pattern?

```{r echo=TRUE}
# Remove NA values
data_no_na <- data[!is.na(data$steps), ]

# Calculate average steps per interval
avg_steps_interval <- aggregate(steps ~ interval, 
                                data = data_no_na, 
                                mean)

# Time series plot
plot(avg_steps_interval$interval,
     avg_steps_interval$steps,
     type = "l",
     main = "Average Steps per 5-minute Interval",
     xlab = "5-minute Interval",
     ylab = "Average Number of Steps")

# Find interval with maximum average steps
max_interval <- avg_steps_interval[which.max(avg_steps_interval$steps), ]

max_interval
```

---

## Imputing missing values

```{r echo=TRUE}
# Count total NA values
total_na <- sum(is.na(data$steps))
total_na

# Create dataset for imputation
data_imputed <- data

# Calculate mean for each interval
interval_means <- aggregate(steps ~ interval,
                            data = data,
                            mean,
                            na.rm = TRUE)

# Replace NA with interval mean
for (i in 1:nrow(data_imputed)) {
  if (is.na(data_imputed$steps[i])) {
    interval_value <- data_imputed$interval[i]
    data_imputed$steps[i] <- interval_means$steps[
      interval_means$interval == interval_value
    ]
  }
}

# Calculate total steps per day (imputed data)
total_steps_imputed <- aggregate(steps ~ date,
                                 data = data_imputed,
                                 sum)

# Histogram after imputation
hist(total_steps_imputed$steps,
     main = "Histogram of Total Steps per Day (Imputed)",
     xlab = "Total Steps per Day",
     col = "lightgreen")

# Mean and median after imputation
mean_imputed <- mean(total_steps_imputed$steps)
median_imputed <- median(total_steps_imputed$steps)

mean_imputed
median_imputed
```

---

## Are there differences in activity patterns between weekdays and weekends?

```{r echo=TRUE}
# Convert date to Date format
data_imputed$date <- as.Date(data_imputed$date)

# Create weekday/weekend variable
data_imputed$day_type <- ifelse(weekdays(data_imputed$date) %in% 
                                  c("Saturday", "Sunday"),
                                "weekend",
                                "weekday")

data_imputed$day_type <- as.factor(data_imputed$day_type)

# Average steps per interval by day type
avg_steps_daytype <- aggregate(steps ~ interval + day_type,
                               data = data_imputed,
                               mean)

# Separate weekday and weekend data
weekday_data <- avg_steps_daytype[avg_steps_daytype$day_type == "weekday", ]
weekend_data <- avg_steps_daytype[avg_steps_daytype$day_type == "weekend", ]

# Create panel plot
par(mfrow = c(2,1))

plot(weekday_data$interval,
     weekday_data$steps,
     type = "l",
     main = "Average Steps per Interval (Weekday)",
     xlab = "5-minute Interval",
     ylab = "Average Steps")

plot(weekend_data$interval,
     weekend_data$steps,
     type = "l",
     main = "Average Steps per Interval (Weekend)",
     xlab = "5-minute Interval",
     ylab = "Average Steps")

par(mfrow = c(1,1))
```